<a href="https://colab.research.google.com/github/ssuriya007/sirpi/blob/main/Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x = 10
b = "test"

In [ ]:
print(x)
b

10


'test'

In [ ]:
print("My given input is:",x)

My given input is: 10


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/suriya/Automobile.csv")


In [ ]:
import pandas as pd
import numpy as np
df

symboling  normalized_losses         make fuel_type aspiration  \
0            3                168  alfa-romero       gas        std   
1            3                168  alfa-romero       gas        std   
2            1                168  alfa-romero       gas        std   
3            2                164         audi       gas        std   
4            2                164         audi       gas        std   
..         ...                ...          ...       ...        ...   
196         -1                 95        volvo       gas        std   
197         -1                 95        volvo       gas      turbo   
198         -1                 95        volvo       gas        std   
199         -1                 95        volvo    diesel      turbo   
200         -1                 95        volvo       gas      turbo   

    number_of_doors   body_style drive_wheels engine_location  wheel_base  \
0               two  convertible          rwd           front        88.6   
1               two  convertible          rwd           front        88.6   
2               two    hatchback          rwd           front        94.5   
3              four        sedan          fwd           front        99.8   
4              four        sedan          4wd           front        99.4   
..              ...          ...          ...             ...         ...   
196            four        sedan          rwd           front       109.1   
197            four        sedan          rwd           front       109.1   
198            four        sedan          rwd           front       109.1   
199            four        sedan          rwd           front       109.1   
200            four        sedan          rwd           front       109.1   

     ...  engine_size  fuel_system  bore  stroke compression_ratio horsepower  \
0    ...          130         mpfi  3.47    2.68               9.0        111   
1    ...          130         mpfi  3.47    2.68               9.0        111   
2    ...          152         mpfi  2.68    3.47               9.0        154   
3    ...          109         mpfi  3.19    3.40              10.0        102   
4    ...          136         mpfi  3.19    3.40               8.0        115   
..   ...          ...          ...   ...     ...               ...        ...   
196  ...          141         mpfi  3.78    3.15               9.5        114   
197  ...          141         mpfi  3.78    3.15               8.7        160   
198  ...          173         mpfi  3.58    2.87               8.8        134   
199  ...          145          idi  3.01    3.40              23.0        106   
200  ...          141         mpfi  3.78    3.15               9.5        114   

     peak_rpm city_mpg  highway_mpg  price  
0        5000       21           27  13495  
1        5000       21           27  16500  
2        5000       19           26  16500  
3        5500       24           30  13950  
4        5500       18           22  17450  
..        ...      ...          ...    ...  
196      5400       23           28  16845  
197      5300       19           25  19045  
198      5500       18           23  21485  
199      4800       26           27  22470  
200      5400       19           25  22625  

[201 rows x 26 columns]

In [ ]:
df.fillna()

In [ ]:
df.head(2)

symboling  normalized_losses         make fuel_type aspiration  \
0          3                168  alfa-romero       gas        std   
1          3                168  alfa-romero       gas        std   

  number_of_doors   body_style drive_wheels engine_location  wheel_base  ...  \
0             two  convertible          rwd           front        88.6  ...   
1             two  convertible          rwd           front        88.6  ...   

   engine_size  fuel_system  bore  stroke compression_ratio horsepower  \
0          130         mpfi  3.47    2.68               9.0        111   
1          130         mpfi  3.47    2.68               9.0        111   

   peak_rpm city_mpg  highway_mpg  price  
0      5000       21           27  13495  
1      5000       21           27  16500  

[2 rows x 26 columns]

In [ ]:
df.tail(6)

symboling  normalized_losses   make fuel_type aspiration number_of_doors  \
195         -1                 74  volvo       gas      turbo            four   
196         -1                 95  volvo       gas        std            four   
197         -1                 95  volvo       gas      turbo            four   
198         -1                 95  volvo       gas        std            four   
199         -1                 95  volvo    diesel      turbo            four   
200         -1                 95  volvo       gas      turbo            four   

    body_style drive_wheels engine_location  wheel_base  ...  engine_size  \
195      wagon          rwd           front       104.3  ...          130   
196      sedan          rwd           front       109.1  ...          141   
197      sedan          rwd           front       109.1  ...          141   
198      sedan          rwd           front       109.1  ...          173   
199      sedan          rwd           front       109.1  ...          145   
200      sedan          rwd           front       109.1  ...          141   

     fuel_system  bore  stroke compression_ratio horsepower  peak_rpm  \
195         mpfi  3.62    3.15               7.5        162      5100   
196         mpfi  3.78    3.15               9.5        114      5400   
197         mpfi  3.78    3.15               8.7        160      5300   
198         mpfi  3.58    2.87               8.8        134      5500   
199          idi  3.01    3.40              23.0        106      4800   
200         mpfi  3.78    3.15               9.5        114      5400   

    city_mpg  highway_mpg  price  
195       17           22  18950  
196       23           28  16845  
197       19           25  19045  
198       18           23  21485  
199       26           27  22470  
200       19           25  22625  

[6 rows x 26 columns]

In [ ]:
print("No of Rows:", df.shape[0])

No of Rows: 201


In [ ]:
df.shape

(201, 26)

In [ ]:
df.shape[1]

26

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   symboling            201 non-null    int64  
 1   normalized_losses    201 non-null    int64  
 2   make                 201 non-null    object 
 3   fuel_type            201 non-null    object 
 4   aspiration           201 non-null    object 
 5   number_of_doors      201 non-null    object 
 6   body_style           201 non-null    object 
 7   drive_wheels         201 non-null    object 
 8   engine_location      201 non-null    object 
 9   wheel_base           201 non-null    float64
 10  length               201 non-null    float64
 11  width                201 non-null    float64
 12  height               201 non-null    float64
 13  curb_weight          201 non-null    int64  
 14  engine_type          201 non-null    object 
 15  number_of_cylinders  201 non-null    obj

In [ ]:
df.isnull().sum()

symboling              0
normalized_losses      0
make                   0
fuel_type              0
aspiration             0
number_of_doors        0
body_style             0
drive_wheels           0
engine_location        0
wheel_base             0
length                 0
width                  0
height                 0
curb_weight            0
engine_type            0
number_of_cylinders    0
engine_size            0
fuel_system            0
bore                   0
stroke                 0
compression_ratio      0
horsepower             0
peak_rpm               0
city_mpg               0
highway_mpg            0
price                  0
dtype: int64

In [ ]:
df["fuel_system"].unique()

array(['mpfi', '2bbl', 'mfi', '1bbl', 'spfi', '4bbl', 'idi', 'spdi'],
      dtype=object)

In [ ]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_testing',
 '_typing',
 '_version',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'c

In [ ]:
df.loc[0:5,"bore":"stroke"]

bore  stroke
0  3.47    2.68
1  3.47    2.68
2  2.68    3.47
3  3.19    3.40
4  3.19    3.40
5  3.19    3.40

In [ ]:
df.iloc[0:5,-8:-6]

bore  stroke
0  3.47    2.68
1  3.47    2.68
2  2.68    3.47
3  3.19    3.40
4  3.19    3.40

In [ ]:
df.columns

Index(['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration',
       'number_of_doors', 'body_style', 'drive_wheels', 'engine_location',
       'wheel_base', 'length', 'width', 'height', 'curb_weight', 'engine_type',
       'number_of_cylinders', 'engine_size', 'fuel_system', 'bore', 'stroke',
       'compression_ratio', 'horsepower', 'peak_rpm', 'city_mpg',
       'highway_mpg', 'price'],
      dtype='object')

In [ ]:
df['city_mpg'].mean()#for finding the average

25.17910447761194

In [ ]:
df['make'].to_string()

'0        alfa-romero\n1        alfa-romero\n2        alfa-romero\n3               audi\n4               audi\n5               audi\n6               audi\n7               audi\n8               audi\n9                bmw\n10               bmw\n11               bmw\n12               bmw\n13               bmw\n14               bmw\n15               bmw\n16               bmw\n17         chevrolet\n18         chevrolet\n19         chevrolet\n20             dodge\n21             dodge\n22             dodge\n23             dodge\n24             dodge\n25             dodge\n26             dodge\n27             dodge\n28             dodge\n29             honda\n30             honda\n31             honda\n32             honda\n33             honda\n34             honda\n35             honda\n36             honda\n37             honda\n38             honda\n39             honda\n40             honda\n41             honda\n42             isuzu\n43             isuzu\n44            jaguar\n45       

In [ ]:
df['make'].max()

'volvo'

In [ ]:
df['make'].min()

'alfa-romero'

In [ ]:
df['number_of_doors'].to_string()

'0       two\n1       two\n2       two\n3      four\n4      four\n5       two\n6      four\n7      four\n8      four\n9       two\n10     four\n11      two\n12     four\n13     four\n14     four\n15      two\n16     four\n17      two\n18      two\n19     four\n20      two\n21      two\n22      two\n23     four\n24     four\n25     four\n26      two\n27     four\n28      two\n29      two\n30      two\n31      two\n32      two\n33      two\n34     four\n35     four\n36      two\n37      two\n38     four\n39     four\n40     four\n41      two\n42     four\n43      two\n44     four\n45     four\n46      two\n47      two\n48      two\n49      two\n50     four\n51     four\n52      two\n53      two\n54      two\n55      two\n56      two\n57     four\n58      two\n59     four\n60     four\n61     four\n62     four\n63     four\n64     four\n65     four\n66      two\n67     four\n68     four\n69      two\n70     four\n71      two\n72      two\n73      two\n74      two\n75      two\n76      two

In [ ]:
min=df['price'].min()
max=df['price'].max()
print(min,max,sep=",")
df['price']
df.loc[0:200,"price"].min()

5118,45400


5118

In [ ]:
df['price']

0      13495
1      16500
2      16500
3      13950
4      17450
       ...  
196    16845
197    19045
198    21485
199    22470
200    22625
Name: price, Length: 201, dtype: int64

write Python code to:
•	Load the CSV file into a Pandas DataFrame.
•	Display the first 30 rows.
•	Print column names.
•	Print No of Rows & Columns
•	Find the Data Types of every column & check if there are any mismatch
•	What are the minimum & maximum price of the car & state fuel type they belong to
•	List all the unique engine types
•	Find the horsepower range
•	What is the average mpg in cities & highway. Which is better?
•	What are the different Automobile makes present & which has maximum count

In [ ]:
c=df['price'].min()

In [ ]:
v=df['price'].max()
print(c,v)

5118 45400


In [ ]:
f = df[df["price"] == c]["fuel_type"]
f2 = df[df["price"] == v]["fuel_type"]
print(f,f2)
#fuel_type

134    gas
Name: fuel_type, dtype: object 71    gas
Name: fuel_type, dtype: object


In [ ]:
["fuel_type"].values

In [ ]:
df["fuel_type"].values

array(['gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas',
       'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas',
       'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas',
       'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas',
       'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas',
       'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas',
       'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'diesel', 'gas', 'gas',
       'diesel', 'diesel', 'diesel', 'diesel', 'diesel', 'gas', 'gas',
       'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas',
       'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'diesel',
       'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas',
       'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'diesel',
       'gas', 'diesel', 'gas', 'diesel', 'gas', 'diesel', 'gas', 'diesel',
       'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas',
     

In [ ]:
df['fuel_type']

0         gas
1         gas
2         gas
3         gas
4         gas
        ...  
196       gas
197       gas
198       gas
199    diesel
200       gas
Name: fuel_type, Length: 201, dtype: object

In [ ]:
min=df['price'].min()
df.loc[df['price']==min, ('price',"fuel_type")]

price fuel_type
134   5118       gas

In [ ]:
df.loc[df['price']==v,('price',"fuel_type")]

price fuel_type
71  45400       gas

In [ ]:
df['engine_type'].unique()

array(['dohc', 'ohcv', 'ohc', 'l', 'rotor', 'ohcf'], dtype=object)

In [ ]:
df.nunique()

symboling                6
normalized_losses       58
make                    22
fuel_type                2
aspiration               2
number_of_doors          2
body_style               5
drive_wheels             3
engine_location          2
wheel_base              52
length                  73
width                   43
height                  49
curb_weight            169
engine_type              6
number_of_cylinders      7
engine_size             43
fuel_system              8
bore                    39
stroke                  36
compression_ratio       32
horsepower              58
peak_rpm                22
city_mpg                29
highway_mpg             30
price                  186
dtype: int64

In [ ]:
df['horsepower'].describe().T

count    201.000000
mean     103.263682
std       37.389372
min       48.000000
25%       70.000000
50%       95.000000
75%      116.000000
max      262.000000
Name: horsepower, dtype: float64

In [ ]:
highway=df['highway_mpg'].mean()
print(highway)
city=df['city_mpg'].mean()
print(city)
print('highway'if highway>city else 'city')

30.686567164179106
25.17910447761194
highway


In [ ]:
df.columns

Index(['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration',
       'number_of_doors', 'body_style', 'drive_wheels', 'engine_location',
       'wheel_base', 'length', 'width', 'height', 'curb_weight', 'engine_type',
       'number_of_cylinders', 'engine_size', 'fuel_system', 'bore', 'stroke',
       'compression_ratio', 'horsepower', 'peak_rpm', 'city_mpg',
       'highway_mpg', 'price'],
      dtype='object')

In [ ]:
f=df['make'].value_counts().reset_index()
f

make  count
0          toyota     32
1          nissan     18
2           mazda     17
3      mitsubishi     13
4           honda     13
5      volkswagen     12
6          subaru     12
7          peugot     11
8           volvo     11
9           dodge      9
10  mercedes-benz      8
11            bmw      8
12       plymouth      7
13           audi      6
14           saab      6
15        porsche      4
16         jaguar      3
17      chevrolet      3
18    alfa-romero      3
19          isuzu      2
20        renault      2
21        mercury      1

2. Accessing Data with .loc[]
Using the following DataFrame:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, 27, 22, 32],
    "Score": [85, 90, 78, 88]
})
Task
•	Retrieve the row where Name == "Charlie" using .loc[].
•	Select only the Age and Score columns for "Alice" and "Bob" using .loc[].


In [ ]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, 27, 22, 32],
    "Score": [85, 90, 78, 88]})
d=df.loc[df['Name']=='Charlie']
print(d)

      Name  Age  Score
2  Charlie   22     78


In [ ]:
i=df.loc[df["Name"].isin(["Alice", "Bob"]), ["Age", "Score"]]
print(i)

   Age  Score
0   24     85
1   27     90


3. Accessing Data with .iloc[]
Using the same DataFrame from Question 2, write code to:
•	Retrieve the second row using .iloc[].
•	Extract the last two rows using .iloc[].


In [ ]:
s=df.iloc[1]
print(s)

Name     Bob
Age       27
Score     90
Name: 1, dtype: object


In [ ]:
z=df.iloc[-2]
print(z)

Name     Charlie
Age           22
Score         78
Name: 2, dtype: object


4. Filtering Rows Based on Conditions
Using the following DataFrame:
df = pd.DataFrame({
    "Employee": ["John", "Alice", "Bob", "David"],
    "Salary": [50000, 60000, 55000, 65000],
    "Department": ["IT", "HR", "IT", "Finance"]
})
Task
Write a Pandas command to:
•	Select only IT employees.
•	Select employees with a salary greater than 55,000.

In [ ]:
df = pd.DataFrame({
    "Employee": ["John", "Alice", "Bob", "David"],
    "Salary": [50000, 60000, 55000, 65000],
    "Department": ["IT", "HR", "IT", "Finance"]})


In [ ]:
w=df.loc[df['Department']=='IT']
print(w)

  Employee  Salary Department
0     John   50000         IT
2      Bob   55000         IT


In [ ]:
d=(df.loc[df['Salary']>=55000])
print(d)

  Employee  Salary Department
1    Alice   60000         HR
2      Bob   55000         IT
3    David   65000    Finance


In [ ]:
e=df.loc[df['Salary']>55000]
print(e)

  Employee  Salary Department
1    Alice   60000         HR
3    David   65000    Finance


5. Applying Functions to a Column
Using the following DataFrame:
df = pd.DataFrame({
    "Student": ["A", "B", "C", "D"],
    "Marks": [45, 78, 62, 90]
})
Task
Write a function that:
•	Converts marks below
•	"50 to "Fail", and 50 or above to "Pass".
•	Apply this function to the "Marks" column and create a new column Result


In [ ]:
 df = pd.DataFrame({ "Student": ["A", "B", "C", "D"], "Marks": [45, 78, 62, 90] })
def grade(j):
       return"pass" if j>=50 else "fail"

df["R"] = df["Marks"].apply(grade)
print(df)


  Student  Marks     R
0       A     45  fail
1       B     78  pass
2       C     62  pass
3       D     90  pass


In [ ]:
def abc(st):
    return 0 if st=="fail" else 100

In [ ]:
df["ABC"] = df["R"].apply(abc)
df

Student  Marks     R  ABC
0       A     45  fail    0
1       B     78  pass  100
2       C     62  pass  100
3       D     90  pass  100

In [ ]:
grade(30)

'fail'

. NumPy - Creating and Reshaping Arrays
Write Python code to:
•	Create a NumPy array with values from 1 to 12.
•	Reshape it into a 3x4 matrix.

In [ ]:
import numpy as np
arr= np.arange(1,13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


7. NumPy - Broadcasting & Element-wise Operations
You are given the following NumPy arrays:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
Task
Perform:
1.	Element-wise multiplication of a and b.
2.	Add 5 to each element of a using broadcasting


In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(a*b)
print(a+5)
print(b+5)


[10 40 90]
[6 7 8]
[15 25 35]


8. Finding Maximum and Minimum Values in a NumPy Array
Given:
arr = np.array([[3, 7, 2], [4, 9, 6]])
Task
•	Find the maximum value in the entire array.
•	Find the minimum value in each row


In [ ]:
arr = np.array([[3, 7, 2], [4, 9, 6]])
d=arr.min()
d
print(arr)
f1=arr.min(axis=1)
f1

[[3 7 2]
 [4 9 6]]


array([2, 4])

9. Grouping & Aggregation in Pandas
You have the following DataFrame:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [70000, 50000, 80000, 60000, 52000]
})
Task
Write a Pandas command to:
•	Group the DataFrame by "Department" and calculate the average salary per department


In [ ]:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [70000, 50000, 80000, 60000, 52000]
})


In [ ]:
print(df.groupby("Department")['Salary'].mean())

Department
Finance    60000.0
HR         51000.0
IT         75000.0
Name: Salary, dtype: float64


10. Sorting a DataFrame
Given the following DataFrame:
df = pd.DataFrame({
    "City": ["New York", "Los Angeles", "Chicago", "Houston"],
    "Population": [8419600, 3980400, 2716000, 2328000]
})
Task
•	Sort the DataFrame by Population in descending order.


In [ ]:
df = pd.DataFrame({
    "City": ["New York", "Los Angeles", "Chicago", "Houston"],
    "Population": [8419600, 3980400, 2716000, 2328000]
})
print(df.sort_values("Population",ascending=False))

          City  Population
0     New York     8419600
1  Los Angeles     3980400
2      Chicago     2716000
3      Houston     2328000


11. Multi-Indexing in Pandas
You are given the following DataFrame:
data = {
    "Region": ["North", "North", "South", "South", "East", "East"],
    "City": ["A", "B", "A", "B", "A", "B"],
    "Sales": [200, 150, 180, 220, 300, 250]
}
df = pd.DataFrame(data).set_index(["Region", "City"])
Task
•	Retrieve the sales value for City A in the South Region using multi-indexing.
________________________________________


In [ ]:
data = {
    "Region": ["North", "North", "South", "South", "East", "East"],
    "City": ["A", "B", "A", "B", "A", "B"],
    "Sales": [200, 150, 180, 220, 300, 250]
}
df = pd.DataFrame(data).set_index(["Region", "City"])

In [ ]:
print(df.loc['South','A'],"Sales")

Sales    180
Name: (South, A), dtype: int64 Sales


12. Creating a DataFrame from a NumPy Array
Generate a 5x4 NumPy array with random integers between 10 and 99 and convert it into a Pandas DataFrame with column names ["A", "B", "C", "D"].


In [ ]:
sd=np.random.randint(low=10,high=99,size=(5,4))
print(pd.DataFrame(sd,columns=['A','B','C','D']))

    A   B   C   D
0  26  64  66  91
1  25  88  47  11
2  59  53  35  79
3  16  69  17  43
4  72  85  74  64


13. Conditional Column Update
Given the following DataFrame:
df = pd.DataFrame({
    "Student": ["Alice", "Bob", "Charlie", "David"],
    "Marks": [88, 45, 76, 90],
    "Attendance": [85, 50, 90, 60]
})
Task
Write a one-liner Pandas command to set "Marks" to 0 for students whose "Attendance" is less than 60.
________________________________________


In [ ]:
df = pd.DataFrame({
    "Student": ["Alice", "Bob", "Charlie", "David"],
    "Marks": [88, 45, 76, 90],
    "Attendance": [85, 50, 90, 60]
})

In [ ]:
a=(df['Attendance']<60,'Marks')


(0    False
 1     True
 2    False
 3    False
 Name: Attendance, dtype: bool,
 'Marks')

In [ ]:
df.loc[df['Attendance'] < 60, 'Marks'] = 0
print(df)

   Student  Marks  Attendance
0    Alice     88          85
1      Bob      0          50
2  Charlie     76          90
3    David     90          60


14. Advanced Filtering
From a CSV file "employees.csv" with columns:
EmployeeID, Department, Salary, Experience (in years).
Note: You should create “employees.csv” & perform the below task


In [ ]:
data = {'EmployeeID': [1, 2, 3, 4, 5, 6],
        'Department': ['IT', 'Sales', 'IT', 'HR', 'Sales', 'IT'],
        'Salary': [60000, 50000, 70000, 55000, 62000, 80000],
        'Experience': [3, 1, 5, 2, 4, 6]}
df = pd.DataFrame(data)
df.to_csv('employees.csv', index=False)
employees_df = pd.read_csv('employees.csv')
filtered_df = employees_df[(employees_df['Department'] == 'IT') &
                           (employees_df['Experience'] >=5) &
                           (employees_df['Salary'] > 60000)]
print(filtered_df)


   EmployeeID Department  Salary  Experience
2           3         IT   70000           5
5           6         IT   80000           6


In [ ]:
#Grouping & Aggregation with Multiple Conditions
import pandas as pd
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance", "IT"],
    "Salary": [70000, 50000, 80000, 60000, 52000, 72000, 65000],
    "Experience": [5, 4, 7, 3, 2, 8, 6]
})
filtered_df = df[df['Experience'] >= 5]
sant=filtered_df.groupby('Department')['Salary'].mean()
print(sant)


Department
Finance    72000.000000
IT         71666.666667
Name: Salary, dtype: float64


In [ ]:
#NumPy - Complex Indexing
import numpy as np
df=np.random.randint(low=0,high=100,size=(5,5))
df


array([[58, 45, 48, 53, 23],
       [33, 28, 16, 94, 32],
       [65, 97, 60, 40, 69],
       [84, 96, 56, 89, 24],
       [96, 29, 63, 68, 85]])

16. NumPy - Complex Indexing
Create a 5x5 NumPy array with random values between 1 and 100.
Write a NumPy command to:
Extract only even numbers from the array.
Extract values from the last row and last column.
Replace all values greater than 50 with 0.

In [ ]:
import numpy as np
# Create a 5x5 NumPy array with random values between 1 and 100
arr = np.random.randint(1, 100, size=(5, 5))

# Extract only even numbers from the array
even_numbers = arr[arr % 2 == 0]

# Extract values from the last row and last column
last_row = arr[-1, :]
last_column = arr[:, -1]

# Replace all values greater than 50 with 0
arr[arr > 50] = 0

print("Original array:\n", arr)
print("\nEven numbers:\n", even_numbers)
print("\nLast row:\n", last_row)
print("\nLast column:\n", last_column)
print("\nArray with values > 50 replaced by 0:\n", arr)


Original array:
 [[47 40  0 17 29]
 [ 0 18 31  0 31]
 [ 0 39  0  0  0]
 [25 37  0 15 43]
 [37  0 23  0 23]]

Even numbers:
 [40 68 18 74 62]

Last row:
 [37  0 23  0 23]

Last column:
 [29 31  0 43 23]

Array with values > 50 replaced by 0:
 [[47 40  0 17 29]
 [ 0 18 31  0 31]
 [ 0 39  0  0  0]
 [25 37  0 15 43]
 [37  0 23  0 23]]
